server:
  port: 8090
logging:
  level:
    root: INFO
spring:
  application:
    name: consume-movie

#Actuator 健康检查详情
management:
  security:
    enabled: false

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@discovery:8000/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true


#服务地址
user:
  userServiceUrl: http://peer1:8080/
#feign:
#  client:
#    config:
#      feignName:
#        #相当于Request.Options
#        connectTimeout: 5000
#        readTimeout: 5000
#        #配置Feign的日志级别
#        loggerLevel: full
#        #Feign的错误解码器,相当于代码配置方式中的ErrorDecoder
#        errorDecoder: com.example.SimpleErrorDecoder
#        #配置重试,相当于代码中配置方式中的Retryer
#        retryer: com.example.SimpleRetryer
#        # 配置拦截器,相当于代码配置方式中的RequestInteceptor
#        requestInterceptors:
#          - com.example.fooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false
#默认配置
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
