server:
  port: 8060
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@discovery:8000/eureka
  instance:
    prefer-ip-address: true
  management:
    security:
      enabled: false
#zuul:
#  routes:
#    provider-user-nologin: /user/**
#  ignored-services: consumer-movie-ribbon


#同时指定path和URL且不破坏Zuul的Hystrix,Ribbon特性
#zuul:
#  routes:
#    #仅命名
#    user-route:
#      path: /user/**
#      service-id: provider-user-nologin

#ribbon:
#  eureka: false
#  ConnectTimeout: 3000
#  ReadTimeout: 60000
#provider-user-nologin:
#  ribbon:
#    listOfServers: discovery:8000,discovery-eureka:8001
logging:
  level:
    com.netflix: DEBUG
#设置超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

#路由前缀
#zuul:
#  prefix: /api
#  strip-prefix: false
#  routes:

#    provider-user-nologin: /user/**

#饥饿加载
zuul:
  ribbon:
    eager-load:
      enabled: true
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true